// Code generated by "stringer -type=DoorHinge -output=door_hinge_side_string.go"; DO NOT EDIT.

package properties

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DoorHingeLeft-0]
	_ = x[DoorHingeRight-1]
}

const _DoorHinge_name = "DoorHingeLeftDoorHingeRight"

var _DoorHinge_index = [...]uint8{0, 13, 27}

func (i DoorHinge) String() string {
	if i >= DoorHinge(len(_DoorHinge_index)-1) {
		return "DoorHinge(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DoorHinge_name[_DoorHinge_index[i]:_DoorHinge_index[i+1]]
}
