// Code generated by "stringer -type=PistonType -output=piston_type_string.go"; DO NOT EDIT.

package properties

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PistonTypeDefault-0]
	_ = x[PistonTypeSticky-1]
}

const _PistonType_name = "PistonTypeDefaultPistonTypeSticky"

var _PistonType_index = [...]uint8{0, 17, 33}

func (i PistonType) String() string {
	if i >= PistonType(len(_PistonType_index)-1) {
		return "PistonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PistonType_name[_PistonType_index[i]:_PistonType_index[i+1]]
}
