// Code generated by generator/blocks/main.go; DO NOT EDIT.
package states

var (
	SnowyProperty = NewBooleanProperty("snowy")

	StageProperty = NewIntegerProperty("stage", 0, 1)

	Age4Property = NewIntegerProperty("age", 0, 4)

	HangingProperty = NewBooleanProperty("hanging")

	WaterloggedProperty = NewBooleanProperty("waterlogged")

	LevelProperty = NewIntegerProperty("level", 0, 15)

	DistanceProperty = NewIntegerProperty("distance", 1, 7)

	PersistentProperty = NewBooleanProperty("persistent")

	TriggeredProperty = NewBooleanProperty("triggered")

	NoteProperty = NewIntegerProperty("note", 0, 24)

	PoweredProperty = NewBooleanProperty("powered")

	OccupiedProperty = NewBooleanProperty("occupied")

	ExtendedProperty = NewBooleanProperty("extended")

	ShortProperty = NewBooleanProperty("short")

	UnstableProperty = NewBooleanProperty("unstable")

	Age15Property = NewIntegerProperty("age", 0, 15)

	EastProperty = NewBooleanProperty("east")

	NorthProperty = NewBooleanProperty("north")

	SouthProperty = NewBooleanProperty("south")

	UpProperty = NewBooleanProperty("up")

	WestProperty = NewBooleanProperty("west")

	PowerProperty = NewIntegerProperty("power", 0, 15)

	Age7Property = NewIntegerProperty("age", 0, 7)

	MoistureProperty = NewIntegerProperty("moisture", 0, 7)

	LitProperty = NewBooleanProperty("lit")

	RotationProperty = NewIntegerProperty("rotation", 0, 15)

	OpenProperty = NewBooleanProperty("open")

	LayersProperty = NewIntegerProperty("layers", 1, 8)

	HasRecordProperty = NewBooleanProperty("has_record")

	BitesProperty = NewIntegerProperty("bites", 0, 6)

	DelayProperty = NewIntegerProperty("delay", 1, 4)

	LockedProperty = NewBooleanProperty("locked")

	DownProperty = NewBooleanProperty("down")

	InWallProperty = NewBooleanProperty("in_wall")

	Age3Property = NewIntegerProperty("age", 0, 3)

	HasBottle0Property = NewBooleanProperty("has_bottle_0")

	HasBottle1Property = NewBooleanProperty("has_bottle_1")

	HasBottle2Property = NewBooleanProperty("has_bottle_2")

	EyeProperty = NewBooleanProperty("eye")

	Age2Property = NewIntegerProperty("age", 0, 2)

	AttachedProperty = NewBooleanProperty("attached")

	DisarmedProperty = NewBooleanProperty("disarmed")

	ConditionalProperty = NewBooleanProperty("conditional")

	InvertedProperty = NewBooleanProperty("inverted")

	EnabledProperty = NewBooleanProperty("enabled")

	Age5Property = NewIntegerProperty("age", 0, 5)

	Age25Property = NewIntegerProperty("age", 0, 25)

	EggsProperty = NewIntegerProperty("eggs", 1, 4)

	HatchProperty = NewIntegerProperty("hatch", 0, 2)

	PicklesProperty = NewIntegerProperty("pickles", 1, 4)

	Age1Property = NewIntegerProperty("age", 0, 1)

	DragProperty = NewBooleanProperty("drag")

	BottomProperty = NewBooleanProperty("bottom")

	HasBookProperty = NewBooleanProperty("has_book")

	SignalFireProperty = NewBooleanProperty("signal_fire")

	HoneyLevelProperty = NewIntegerProperty("honey_level", 0, 5)

	ChargesProperty = NewIntegerProperty("charges", 0, 4)

	CandlesProperty = NewIntegerProperty("candles", 1, 4)

	BloomProperty = NewBooleanProperty("bloom")

	CanSummonProperty = NewBooleanProperty("can_summon")

	ShriekingProperty = NewBooleanProperty("shrieking")

	BerriesProperty = NewBooleanProperty("berries")
)
